export default {
  // data
  INITIAL_DATA: "INITIAL_DATA",
  UPDATE_DATA: "UPDATE_DATA",
  ADD_ITEM_DATA: "ADD_ITEM_DATA",

  // Obj for deleting
  SET_OBJ_FOR_DELETING: "SET_OBJ_FOR_DELETING",
  CLEAR_OBJID_FOR_DELETING: "CLEAR_OBJ_FOR_DELETING",

  // Change
  CHANGE_SORT: "CHANGE_SORT",
  CHANGE_LOCAL: "CHANGE_LOCAL",
  CHANGE_ITEM_WIDTH: "CHANGE_ITEM_WIDTH",
  CHANGE_MODAL_STATE: "CHANGE_MODAL_STATE",
  SWITCH_THEME: "SWITCH_THEME",

  // Eeditable_obj
  SET_EDITABLE_OBJ: "SET_EDITABLE_OBJ",
  UPDATE_EDITABLE_OBJ: "UPDATE_EDITABLE_OBJ",
  CLEAR_EDITABLE_OBJ: "CLEAR_EDITABLE_OBJ"
};
